clear all

local simulation = `1'

assert inrange(`simulation', 1, 10)
assert `simulation' == int(`simulation')

use "../input/nyc2010_lodes_wzero_wdelta.dta",clear
sort j i

// create id ∈ {1,2,...,4628880} to merge the simulated data
gen id = _n
sum X_ij, d
local pop=`r(sum)'
tempfile LODES2010
save `LODES2010'

import delimited "../temp/individuals_choices_s`simulation'_b1.csv",clear
tempfile tf
save `tf'

foreach i of numlist 2/100 {
import delimited "../temp/individuals_choices_s`simulation'_b`i'.csv",clear
append using `tf'
tempfile tf
save `tf', replace
}
keep if inrange(_n,1,`pop')==1

clonevar id = chosen_choice
collapse (count) X_ij = chosen_choice, by(id)

merge 1:1 id using `LODES2010', assert(match using) keepusing(id i j)
replace X_ij=0 if _merge==2
drop _merge
sort id
sum X_ij,d
assert `pop'==`r(sum)'

// label vars
label var id "id generated by sorting {j,i}"
label var X_ij "Number of commuters residing in i and working in j"
label var i "Tract of residence (11-digit FIPS)"
label var j "Tract of workplace (11-digit FIPS)"
save_data "../temp/realized_commuting_flows_s`simulation'.dta", key(j i) replace log_replace
